import Header from "@/components/shared/Header"
import { AppSidebar } from "@/components/shared/sidebar"
import { SidebarProvider } from "@/components/ui/sidebar"
import { Toaster } from "@/components/ui/sonner"
import QueryProvider from "@/providers/QueryProvider"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "@/components/shared/theme-provider"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
      <QueryProvider>
    <SidebarProvider>
      <div className="flex flex-col min-h-screen w-full">
        
        <Toaster richColors/>
        {/* ১. ফুল উইডথ হেডার */}
        <Header />

        {/* ২. হেডারের নিচের অংশ */}
        <div className="flex flex-1">
          {/* বামে সাইডবার */}
          <AppSidebar />
          
          {/* ডানে মেইন কন্টেন্ট */}
          <main className="flex-1 bg-[#fbfbfb] dark:bg-zinc-950 px-4 py-6">
            {children}
          
          </main>
        </div>
      </div>
    </SidebarProvider>
      </QueryProvider>
      </ThemeProvider>
      </body>
    </html>
  )
}
